
start()
def start() {
  testAcceptance() 
}

def testAcceptance() {
  node('ios') {
    stage ('Clean & Git checkout') {
      deleteDir()
      checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/blacklane/cassandra/']]])
      echo 'Workspace is at: ' + env.BUILD_URL + 'execution/node/3/ws/'
    }
    stage ('Start iOS tests') {
      timeout(time: 30, unit: 'MINUTES') {
        Date now = new Date()
        SimpleDateFormat timestamp = new SimpleDateFormat("dd.mm.dd::HH:mm:ss")
        echo "Running iOS tests..."
        try {
          sh "xcodebuild -workspace Blacklane.xcworkspace -scheme AcceptanceTests -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty --report html --output reports/" + timestamp.format(now) + "_report.html"
        } catch (err) {
          sendBuildFailureEmail(err)
        }
      }
    }
    stage ('Kill simulator') {
      echo "Killing the simulator..."
      sh "killall \"Simulator\""
    }
  }
}

/**
 * Invoked when any build process fails.
 * An email will be sent to the 'committer email' on the last commit.
 */
def sendBuildFailureEmail(err) {
  node('ios') {
    $subject = 'Cassandra Acceptance Tests have failed on'
    $body = '<p>Check failure using link ' + env.BUILD_URL + '</p>'
    $to = ('sofia.vistas@blacklane.com, matthew.bogott@blacklane.com')
    emailext attachLog:false, body:$body, subject:$subject, to:$to, mimeType:'text/html'
    error(err.getMessage())
  }
}